[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.5.4"
actix-web = "3.3.2"
actix-web-httpauth = "0.5.1"
chrono = {version="0.4", features=["serde"]}
derive_more = "0.99.16"
diesel = {version="1.4.8", features= ["postgres","uuidv07", "r2d2","chrono", "numeric"]}
dotenv = "0.15.0"
env_logger = "0.9.0"
r2d2 = "0.8.9"
serde = {version="1.0", features= ["derive"]}
serde_json = "1.0.68"
rand = "0.8.5"
branca = "0.10.0"
getrandom = "0.2.3"
cuid = "1.2.0"
derivative = "2.2.0"
lettre = "0.10.0-rc.4"
maud = "0.23.0"
argon2 = "0.3.3"
diesel-derive-enum = { version = "1", features = ["postgres"]} 
